config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  # https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview#logout-links
  # devise_scope :user do
  # delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  # end

  resources :users, only: %i[index show notifications] do
    get :notifications, on: :member
    resources :friendships, only: %i[create destroy] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
        delete 'remove_friend'
      end
    end
  end

  put '/users/:id', to: 'users#update_img'

  resources :posts, only: %i[index new create show destroy] do
    resources :likes, only: %i[create]
  end

  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :post
  belongs_to :user

  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ApplicationHelper

  def new
    @comment = Comment.new
  end

  def create
    @comment = current_user.comments.build(comment_params)
    @post = Post.find(params[:comment][:post_id])
    return unless @comment.save

    @notification = @post.user.notifications.build(post_id: @post.id,
                                                   notice_id: current_user.id,
                                                   notice_type: 'comment')
    @notification.save
    render partial: 'posts/post', locals: { post: @post }
  end

  def destroy
    @comment = Comment.find(params[:id])
    return unless current_user.id == @comment.user_id

    if @comment.destroy
      Notification.where(notice_id: current_user.id,
                         post_id: @comment.post_id,
                         notice_type: 'comment').first.destroy

      render partial: 'posts/post', locals: { post: Post.find(@comment.post_id) }
    else
      flash.now[:danger] = "Unable to delete comment: #{@comment.errors.full_messages.join(', ')}"
      render turbo_stream: turbo_stream.replace('flash_alert', partial: 'layouts/flash', locals: { flash: })
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class = 'card text-bg-light'>
  <div class="card-header">
    <ul class="nav nav-pills card-header-pills d-flex align-items-center">
      <li class="nav-item" style="max-width: 3rem; max-height: 3rem;">
        <% if comment.user.image? %>
          <%= link_to user_path(comment.user), data: { turbo: false } do %>
            <%= image_tag comment.user.image.url, class: "img-fluid rounded-start" %>
          <% end %>
        <% else %>
          <%# placeholder image %>
          <%= link_to user_path(comment.user), class: 'link-secondary' do %>
            <%= gravatar_for(comment.user, {classlist: 'gravatar img-fluid rounded-start'}) %>
          <% end %>
        <% end %>
      </li>
    
      <li class="nav-item nav-link link-underline-opacity-0 flex-grow-1">
        <%= link_to comment.user.full_name, user_path(comment.user), data: { turbo: false }, class: 'link-secondary fw-bold' %>
        <br>
        <small class="text-secondary">posted <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago</small>
      </li>
      
      <% if current_user == comment.user %>
        <li class="nav-item dropdown">
          <button class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-list link-secondary"></i>
          </button>

          <ul class="dropdown-menu dropdown-menu-end">
            <li><%= button_to 'Delete comment', comment_path(comment), method: :delete, class: 'dropdown-item', data: { turbo_confirm: 'Are you sure you want to delete this comment?' } %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </div>
  
  <div class = 'card-body'>
    <%= comment.content %>
  </div>

  <ul class="list-group list-group-flush">
    <%= render 'likes/comment_likes', comment: comment, current_user: %>


    <li class="list-group-item text-bg-light collapse" id="collapseCommentOnCommentForm<%="#{comment.id}"%>" >
      <%= render 'comments/form', post: Post.find(comment.post_id), parent: comment %>
    </li>

    <% unless comment.replies.empty? %>
        <% ordered_comments = Post.find(comment.post_id).comments
                      .where(parent_id: comment.id)
                      .left_joins(:likes)
                      .group(:id)
                      .order('COUNT(likes.id) DESC') %>

      <li class="list-group-item text-bg-light">
        <p class="text-secondary fs-6 fw-medium lh-1">replies:</p>
        <ul class="list-group">
          <%= render partial: 'comments/comment', collection: comment.replies, as: :comment %>
        </ul>
      </li>
    <% end %>

  </ul>
</div>

<br>

app/views/comments/_form.html.erb
<%= form_for @comment = Comment.new do |f| %>
  <%= render "devise/shared/error_messages", resource: @comment %>

  <%= f.hidden_field :post_id, :value => post.id %>
  <%= f.hidden_field :parent_id, :value => parent.id unless parent.nil? %>

  <div class="input-group mb-2">
    <%= f.text_field :content, class: "comment-box", placeholder: " Write a comment...", class: "form-control" %>
    <%= f.submit 'Submit Comment', class: 'btn btn-primary btn-sm', id: "button-addon2" %>
  </div>
<% end %>