config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  # https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview#logout-links
  # devise_scope :user do
  # delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  # end

  resources :users, only: %i[index show notifications] do
    get :notifications, on: :member
    resources :friendships, only: %i[create destroy] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
        delete 'remove_friend'
      end
    end
  end

  put '/users/:id', to: 'users#update_img'

  resources :posts, only: %i[index new create show destroy] do
    resources :likes, only: %i[create]
  end

  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  mount_uploader :image, UserImageUploader
  validate :picture_size

  after_create :send_welcome_email

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :sent_notifications, class_name: 'Notification',
                                foreign_key: 'notice_id',
                                inverse_of: 'originator',
                                dependent: :destroy

  # BEGIN FRIENDSHIP ASSOCIATIONS
  has_many :sent_friend_requests, class_name: 'Friendship',
                                  foreign_key: 'sent_by_id',
                                  inverse_of: 'sent_by',
                                  dependent: :destroy
  has_many :recieved_friend_requests, class_name: 'Friendship',
                                      foreign_key: 'sent_to_id',
                                      inverse_of: 'sent_to',
                                      dependent: :destroy
  has_many :friends, -> { merge(Friendship.friends) },
           through: :sent_friend_requests, source: :sent_to
  has_many :pending_requests_sent, -> { merge(Friendship.not_friends) },
           through: :sent_friend_requests, source: :sent_to
  has_many :pending_requests_received, -> { merge(Friendship.not_friends) },
           through: :recieved_friend_requests, source: :sent_by
  # END FRIENDSHIP ASSOCIATIONS

  def demo_user?
    email.in?(['humblebragger@humblebrag.com', 'fitnessgrampacer@test.com']) || email.match?(/@wizarding\.world\z/)
  end

  # Returns a string containing this user's first name and last name
  def full_name
    "#{fname} #{lname}"
  end

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.fname = auth.info.name # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.github_data'] && session['devise.github_data']['extra']['raw_info']) && user.email.blank?
        user.email = data['email']
      end
    end
  end

  private

  # Validates the size of an uploaded picture.
  def picture_size
    errors.add(:image, 'should be less than 1MB') if image.size > 1.megabytes
  end

  def send_welcome_email
    WelcomeMailer.with(user: self).welcome_email.deliver_later
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :github

  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :check_demo_account, only: [:destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def check_demo_account
    return unless resource.demo_user?

    redirect_to(root_path, alert: 'Demo accounts cannot be deleted.')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  def index
    @users = User.all

    # for checking which button to render:
    @friends = current_user.friends
    @pending_requests = current_user.pending_requests_sent
    @friend_requests = current_user.pending_requests_received
    @other_users = User.all.reject { |user| user == current_user || possible_friend?(user) }
  end

  def show
    @user = User.find(params[:id])

    # for checking which button to render:
    @friends = current_user.friends
    @pending_requests = current_user.pending_requests_sent
    @friend_requests = current_user.pending_requests_received
    @other_users = User.all.reject { |user| user == current_user || possible_friend?(user) }

    # for pagination:
    @pagy, @posts = pagy_countless(@user.posts.order('created_at desc'), items: 5)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # Might not need anymore:
  # Used in ImageUploadModal which is not being used:
  # def update_img
  #   @user = User.find(params[:id])
  #   unless current_user.id == @user.id
  #     redirect_back(fallback_location: users_path(current_user))
  #     return
  #   end
  #   image = params[:user][:image] unless params[:user].nil?
  #   if image
  #     @user.image = image
  #     if @user.save
  #       flash[:success] = 'Image uploaded'
  #     else
  #       flash[:danger] = "Image upload failed: #{@user.errors.full_messages.join(', ')}"
  #     end
  #   end
  #   redirect_back(fallback_location: root_path)
  # end

  def notifications
    if current_user == User.find(params[:id])
      @new = current_user.notifications.where(viewed?: false).order(created_at: :desc).to_a
      @all = current_user.notifications.order(viewed?: :asc, created_at: :desc)
      @pagy, @notifications = pagy_countless(@all, items: 24)

      respond_to do |format|
        format.html
        format.turbo_stream
      end
    else
      redirect_to notifications_user_path(`current_user`)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Generate default gravatar image
  def gravatar_for(user, options = { size: 80, classlist: nil })
    size = options[:size]
    classlist = options[:classlist]
    gravatar_id  = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=identicon"
    image_tag(gravatar_url, alt: user.full_name, class: classlist)
  end

  # Old default avatar:
  # <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="currentColor" class="bi bi-person-bounding-box" viewBox="0 0 16 16">
  # <path d="M1.5 1a.5.5 0 0 0-.5.5v3a.5.5 0 0 1-1 0v-3A1.5 1.5 0 0 1 1.5 0h3a.5.5 0 0 1 0 1zM11 .5a.5.5 0 0 1 .5-.5h3A1.5 1.5 0 0 1 16 1.5v3a.5.5 0 0 1-1 0v-3a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 1-.5-.5M.5 11a.5.5 0 0 1 .5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 1 0 1h-3A1.5 1.5 0 0 1 0 14.5v-3a.5.5 0 0 1 .5-.5m15 0a.5.5 0 0 1 .5.5v3a1.5 1.5 0 0 1-1.5 1.5h-3a.5.5 0 0 1 0-1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 1 .5-.5"/>
  # <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zm8-9a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
  # </svg>
end

app/views/users/_button.html.erb
<%# Render appropriate button based on relationship with current_user %>
<% if current_user == @user %>
    <%= link_to "Edit profile", edit_user_registration_path, class: 'btn btn-warning' %>
<% else %>
  <% if @friends.include?(user) %>
    <%= button_to 'Remove connection', remove_friend_user_friendships_path(user), method: :delete, class: 'btn btn-outline-secondary btn-sm', data: { turbo_confirm: 'Are you sure you want to remove this friend?' } %>
  <% elsif @pending_requests.include?(user) %>
    <%= button_to 'Cancel connection request', user_friendship_path(id: user, user_id: user), method: :delete, class: 'btn btn-danger btn-sm' %>
  <% elsif @friend_requests.include?(user) %>
    <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#decisionModal<%= user.id %>">Pending connection...</button>
    <%= render 'friendships/decisionModal', user: user %>
  <% elsif @other_users.include?(user) %>
    <%= button_to 'Add connection', user_friendships_path(user), class: 'btn btn-outline-secondary btn-sm' %>
  <% end %>
<% end %>

app/views/users/_usercard.html.erb
<div class="col">
  <div class="card text-center text-bg-light" style="max-width: 540px;">
    <div class="row g-0 d-flex align-items-center">
      
      <div class="col-md-4">
        <% if user.image? %>
          <%= image_tag user.image.url(:thumbnail), class: "img-fluid rounded-start" %>
        <% else %>
          <%= gravatar_for(user, {classlist: 'gravatar img-fluid rounded-start'}) %>
        <% end %>
      </div>
      
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= link_to user.full_name, user_path(user), class: 'nav-link' %></h5>
          <%= render 'button', user: %>
        </div>
      </div>
    </div>

    <%# Render footer for sent and recieved requests %>
    <% if @pending_requests.include?(user) %>
      <div class="card-footer text-body-secondary">
        <%= distance_of_time_in_words(current_user.sent_friend_requests.find_by(sent_to_id: user.id).created_at, Time.now) %> ago
      </div>
    <% elsif @friend_requests.include?(user) %>
      <div class="card-footer text-body-secondary">
        <%= distance_of_time_in_words(current_user.recieved_friend_requests.find_by(sent_by_id:user.id).created_at, Time.now) %> ago
      </div>          
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<div class="card text-center">
  <div class="card-header bg-secondary-subtle">
    <div class="nav nav-tabs" id="nav-tab" role="tablist">

      <% unless @friends.empty? %>
        <button class="nav-link"
                id="friends-tab"
                data-bs-toggle="tab"
                data-bs-target="#friends"
                type="button"
                role="tab"
                aria-controls="friends"
                aria-selected="true">
                  <%= pluralize(@friends.size, 'connection') %>
        </button>
      <% end %>

      <% unless @pending_requests.empty? %>
        <button class="nav-link"
                id="requests-pending-tab"
                data-bs-toggle="tab"
                data-bs-target="#requests-pending"
                type="button"
                role="tab"
                aria-controls="requests-pending"
                aria-selected="false">
                  <%= pluralize(@pending_requests.size, 'connection') %> pending
        </button>
      <% end %>

      <% unless @friend_requests.empty? %>
        <button class="nav-link"
                id="pending-requests-tab"
                data-bs-toggle="tab"
                data-bs-target="#pending-requests"
                type="button"
                role="tab"
                aria-controls="pending-requests"
                aria-selected="false">
                  <%= pluralize(@friend_requests.size, 'pending connection') %>
        </button>
      <% end %>

      <% unless @other_users.empty? %>
        <button class="nav-link active"
                id="find-friends-tab"
                data-bs-toggle="tab"
                data-bs-target="#find-friends"
                type="button"
                role="tab"
                aria-controls="find-friends"
                aria-selected="false">
                  Find new connections
        </button>
      <% end %>

    </div>
  </div>

  <div class="card-body bg-body-secondary">
    <div class="tab-content" id="nav-tabContent">

      <% unless @friends.empty? %>
        <div class="tab-pane fade" id="friends" role="tabpanel" aria-labelledby="friends-tab" tabindex="0">
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <%= render partial: 'usercard', collection: @friends, as: :user %>
          </div>
        </div>
      <% end %>

      <% unless @pending_requests.empty? %>
        <div class="tab-pane fade" id="requests-pending" role="tabpanel" aria-labelledby="requests-pending-tab" tabindex="0">
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <%= render partial: 'usercard', collection: @pending_requests, as: :user %>
          </div>
        </div>
      <% end %>

      <% unless @friend_requests.empty? %>
        <div class="tab-pane fade" id="pending-requests" role="tabpanel" aria-labelledby="pending-requests-tab" tabindex="0">
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <%= render partial: 'usercard', collection: @friend_requests, as: :user %>
          </div>
        </div>
      <% end %>

      <% unless @other_users.empty? %>
        <div class="tab-pane fade show active" id="find-friends" role="tabpanel" aria-labelledby="find-friends-tab" tabindex="0">
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <%= render partial: 'usercard', collection: @other_users.shuffle, as: :user %>
          </div>
        </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/users/notifications.html.erb
<% unless @new.empty? %>
  <h5 class="modal-title" id="noticeModalLabel"><%= pluralize(@new.size, 'new notification') %></h5>
  <br>
<% else %>
  <h5 class="modal-title" id="noticeModalLabel"><%= pluralize(@all.size, 'previous notification') %></h5>
  <br>
<% end %>

<ul id='notifications-display' class="list-group list-group-flush"></ul>
<%= turbo_frame_tag "pagination", src: notifications_user_path(format: :turbo_stream), loading: :lazy %>

<br>

<%# loading icon %>
<div id='loading-icon' class="d-flex justify-content-center align-items-center">
  <div class="spinner-border text-secondary" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

<br><br>

app/views/users/notifications.turbo_stream.erb
<%= turbo_stream.append "notifications-display" do %>
  <%= render partial: "notifications/notification", collection: @notifications %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: notifications_user_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% else %>
  <%= turbo_stream.remove "loading-icon" %>
<% end %>

app/views/users/show.html.erb
<div class = "text-center mx-auto", style="max-width: 200px; max-height: 200px;">
  <% if @user.image? %>
    <%= image_tag @user.image.url, class: "mh-100 mw-100 rounded" %>
  <% else %>
    <%= gravatar_for(@user, {size: 256, classlist: "mh-100 mw-100 rounded"}) %>
    <%# <i class="bi bi-person-bounding-box" style="font-size: 8rem"></i> %>
  <% end %>
</div>

<br><br>

<h3 class = 'text-center'><%= @user.full_name %></h3>

<div class="d-flex justify-content-center">
  <%= render 'button', user: @user %>
</div>

<br>

<div id="user-post-display"></div>
<%= turbo_frame_tag "pagination", src: user_path(@user, format: :turbo_stream), loading: :lazy %>

<%# loading icon %>
<div id='loading-icon' class="d-flex justify-content-center align-items-center">
  <div class="spinner-border text-secondary" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

<br><br>

app/views/users/show.turbo_stream.erb
<%= turbo_stream.append "user-post-display" do %>
  <%= render partial: "posts/post", collection: @posts %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: user_path(@user, page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% else %>
  <%= turbo_stream.remove "loading-icon" %>
<% end %>