config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  # https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview#logout-links
  # devise_scope :user do
  # delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  # end

  resources :users, only: %i[index show notifications] do
    get :notifications, on: :member
    resources :friendships, only: %i[create destroy] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
        delete 'remove_friend'
      end
    end
  end

  put '/users/:id', to: 'users#update_img'

  resources :posts, only: %i[index new create show destroy] do
    resources :likes, only: %i[create]
  end

  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true

  belongs_to :user

  mount_uploader :image, PostImageUploader

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # to produce activerecords for pagination with pagy gem:
  scope :friends_and_own_posts, lambda { |user|
    friend_ids = user.friends.pluck(:id) << user.id
    where(user_id: friend_ids).order(created_at: :desc)
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @pagy, @posts = pagy_countless(Post.friends_and_own_posts(current_user), items: 5)

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      broadcast_post_creation
      flash.now[:success] = 'Post created'
    else
      flash.now[:danger] = "Unable to post: #{@post.errors.full_messages.join(', ')}"
    end
    render turbo_stream: turbo_stream.replace('flash_alert', partial: 'layouts/flash', locals: { flash: })
  end

  def destroy
    @post = Post.find(params[:id])
    return unless current_user.id == @post.user_id

    if @post.destroy
      flash.now[:success] = 'Post deleted'
      render turbo_stream: [
        turbo_stream.remove(@post),
        turbo_stream.replace('flash_alert', partial: 'layouts/flash', locals: { flash: })
      ]
    else
      flash.now[:danger] = "Unable to delete post: #{@post.errors.full_messages.join(', ')}"
      render turbo_stream: turbo_stream.replace('flash_alert', partial: 'layouts/flash', locals: { flash: })
    end
  end

  private

  def broadcast_post_creation
    ActionCable.server.broadcast('post',
                                 ApplicationController.renderer.render(partial: 'posts/post',
                                                                       locals: {
                                                                         post: @post, current_user:
                                                                       }))
  end

  def post_params
    params.require(:post).permit(:content, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="card text-center text-bg-secondary">
  <div class="card-header">
    New post
  </div>

  <div class="card-body mb-2">
    <%# Need to add stimulus controller for data action to reset form: %>
    <%= form_with model: Post, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |f| %>
      <div class="input-group ">
        <%= f.text_field :content, placeholder: ' Write a post...', aria_label: "Recipient's username", aria_describedby: "button-addon2", class: "form-control" %>
        <button type="button" class="btn btn-dark btn-sm" data-bs-toggle="collapse" data-bs-target="#postImageInput" aria-expanded="false" aria-controls="postImageInput">
          <i class="bi bi-image"></i> Add Photo
        </button>
        <%= f.submit 'Submit Post', class: 'btn btn-primary', id: "button-addon2" %>
      </div>

      <div class="field collapse" id="postImageInput">
        <%#= f.label :upload_an_image, class: "form-label" %><br />
        <%= f.hidden_field :image_cache %>
        <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png', class: "form-control"%>
      </div>
    <% end %>  
  </div>
</div>

app/views/posts/_post.html.erb
<%= turbo_frame_tag dom_id(post) do %>
  <div class = 'card text-bg-light'>

    <div class="card-header">
      <ul class="nav nav-pills card-header-pills d-flex align-items-center">
        <li class="nav-item" style="max-width: 3rem; max-height: 3rem;">
          <% if post.user.image? %>
            <%= link_to user_path(post.user), data: { turbo: false }  do %>
              <%= image_tag post.user.image.url, class: "img-fluid rounded-start" %>
            <% end %>
          <% else %>
            <%# placeholder image %>
            <%= link_to user_path(post.user), class: 'link-secondary', data: { turbo: false, turbo_visit_control: 'reload' }  do %>
              <%= gravatar_for(post.user, {classlist: 'gravatar img-fluid rounded-start'}) %>
            <% end %>
          <% end %>
        </li>
        
        <li class="nav-item nav-link link-underline-opacity-0 flex-grow-1">
          <%= link_to post.user.full_name, user_path(post.user), class: 'link-secondary fw-bold', data: { turbo: false } %>
          <br>
          <small class="text-secondary">posted <%= distance_of_time_in_words(post.created_at, Time.now) %> ago</small>
        </li>

        <% if current_user == post.user %>
          <li class="nav-item dropdown">
            <button class="btn btn-light dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-list link-secondary"></i>
            </button>

            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= button_to 'Delete post', post_path(post), method: :delete, class: 'dropdown-item', data: { turbo_confirm: 'Are you sure you want to delete this post?' } %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="row g-0">
      <% if post.image? %>
        <div class="col-md-4">
          <%= image_tag post.image.url, class: 'img-fluid' %>
        </div>
      <% end %>

      <div class = 'card-body <%= 'col-md-8' if post.image? %>'>
        <p><%= post.content %></p>
      </div>
    </div>


    <ul class="list-group list-group-flush">
      <%= render 'likes/post_likes', post: post, current_user: %>

      <li class="list-group-item text-bg-light collapse" id="collapseCommentForm<%="#{post.id}"%>" >
        <%= render 'comments/form', post: post, parent: nil %>
      </li>

      <% unless post.comments.empty? %>
        <% ordered_comments = post.comments
                      .where(parent_id: nil)
                      .left_joins(:likes)
                      .group(:id)
                      .order('COUNT(likes.id) DESC') %>

        <li class="list-group-item text-bg-light">
          <p class="text-secondary fs-6 fw-medium lh-1">comments:</p>
          <%= render partial: 'comments/comment', collection: ordered_comments, as: :comment %>
        </li>
      <% end %>
    </ul>

    <%# <div class="card-footer"></div> %>
  </div>
  <br>
<% end %>

app/views/posts/index.html.erb
<%= render partial: "form" %>

<br>

<div id="post-display">
  <%#= render @posts %>
</div>

<%= turbo_frame_tag "pagination", src: posts_path(format: :turbo_stream), loading: :lazy %>

<%# loading icon %>
<div id='loading-icon' class="d-flex justify-content-center align-items-center">
  <div class="spinner-border text-secondary" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

<br><br>

app/views/posts/index.turbo_stream.erb
<%= turbo_stream.append "post-display" do %>
  <%= render partial: "post", collection: @posts %>
<% end %>

<% if @pagy.next.present? %>
  <%= turbo_stream.replace "pagination" do %>
    <%= turbo_frame_tag "pagination", src: posts_path(page: @pagy.next, format: :turbo_stream), loading: :lazy %>
  <% end %>
<% else %>
  <%= turbo_stream.remove "loading-icon" %>
<% end %>

app/views/posts/show.html.erb
<%= render 'posts/post', post: @post %>