config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  # https://github.com/heartcombo/devise/wiki/OmniAuth:-Overview#logout-links
  # devise_scope :user do
  # delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  # end

  resources :users, only: %i[index show notifications] do
    get :notifications, on: :member
    resources :friendships, only: %i[create destroy] do
      collection do
        get 'accept_friend'
        get 'decline_friend'
        delete 'remove_friend'
      end
    end
  end

  put '/users/:id', to: 'users#update_img'

  resources :posts, only: %i[index new create show destroy] do
    resources :likes, only: %i[create]
  end

  resources :comments, only: %i[new create destroy] do
    resources :likes, only: %i[create]
  end
end

app/views/layouts/_flash.html.erb
<div id="flash_alert">
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, class: "alert alert-#{message_type} alert-dismissible fade show #{"alert-success" if message_type == 'notice'} #{"alert-warning" if message_type == 'alert'}") do %>
      <%= message %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <% end%>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<% if current_user %>
  <nav class="navbar sticky-top navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container-fluid ms-3">
      <%= link_to 'odinbook', posts_path, class: 'navbar-brand' %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Timeline', posts_path, class: 'nav-link' + (' active' if current_page?(posts_path)).to_s %>
          </li>
          
          <li class="nav-item">
            <%= link_to 'Connections', users_path, class: 'nav-link' + (' active' if current_page?(users_path)).to_s %>
          </li>
        </ul>
        
        <ul class="navbar-nav">
          <!---
          <%# icon that displays modal (not currently being used): %>
          <%# if current_user.notifications.where(viewed?: false).empty? %>
            <li class="nav-item d-flex align-items-center" style="cursor: pointer" data-bs-toggle="modal" data-bs-target="#noticeModal">
              <i class="bi bi-bell nav-link"></i>
            </li>
          --->
          <% if current_user.notifications.where(viewed?: false).empty? %>
            <li class="nav-item d-flex align-items-center" style="cursor: pointer">
              <%= link_to notifications_user_path(current_user) do %>
                <i class="bi bi-bell nav-link"></i>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item d-flex align-items-center">
              <%= link_to notifications_user_path(current_user), class: "btn btn-info btn-sm" do %>
                <i class="bi bi-bell"></i> <%= current_user.notifications.where(viewed?: false).count %>
              <% end %>
            </li>
          <% end %>
          
          <li class="nav-item dropdown me-3" style="max-width: 3rem; max-height: 3rem;">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <% if current_user.image? %>
                <%= image_tag current_user.image.url, class: "img-fluid" %>
              <% else %>
                <%# placeholder image %>
                <%= gravatar_for(current_user, {classlist: 'gravatar img-fluid rounded-start'}) %>
              <% end %>
            </a>
            
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= link_to 'My Profile', user_path(current_user), class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'Log out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item' %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <%# allows pop up to appear which shows all notifications the user has %>
  <%#= render 'shared/notifications', notifications: current_user.notifications %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>odinbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class = 'bg-dark-subtle min-vh-100'>
      <%= render 'layouts/nav' %>
      <br>

      <div class = 'container'>
        <%= turbo_frame_tag "flash" do %>
          <%= render 'layouts/flash' %>
        <% end %>
        <%= yield %>
      </div>
    </div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>